# Site settings
title: Grid by Example
email: me@rachelandrew.co.uk
description: "My collection of simple examples of the CSS3 Grid Layout Module."
baseurl: ""
url: "http://gridbyexample.com"
twitter_username: rachelandrew
github_username:  rachelandrew

# Build settings
markdown: kramdown
permalink: pretty